project_id = "ggquxuidarjnayqkhthv"

[functions.send-smtp-email]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.get-gift-details]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false

[functions.create-gift]
verify_jwt = false

[functions.fetch-stock-chart]
verify_jwt = false

[functions.create-alpaca-account]
verify_jwt = false

[functions.create-and-fund-gift]
verify_jwt = false

[functions.retry-gift-funding]
verify_jwt = false

[functions.get-user-portfolio]
verify_jwt = false

[functions.sell-stock]
verify_jwt = false
