// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggquxuidarjnayqkhthv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncXV4dWlkYXJqbmF5cWtodGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTY1NjksImV4cCI6MjA3MDMzMjU2OX0.2CxN1Sj1l8dftUVigcMJXp9jNFfPPfQpE3MVSkAnp4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});